### ISSUE TITLE
Incorrect status returned by get_header routines?

### ISSUE THREAD

**Issue by jbdv-no** [jacobwilliams/fortran-csv-module#17]
To the best of my understanding, there seems to be an error in the value assigned to `status_ok` by the generic `get_header` routines in `csv_module.F90`.  See lines [617](https://github.com/jacobwilliams/fortran-csv-module/blob/edc2061f4c59ddc1fea738c27989f6ecdb0d89ed/src/csv_module.F90#L617) and [648](https://github.com/jacobwilliams/fortran-csv-module/blob/edc2061f4c59ddc1fea738c27989f6ecdb0d89ed/src/csv_module.F90#L648).

After the loops assigning values to the `header` argument, I would expect to find `status_ok = .true.` instead of `status_ok = .false.`? As is, the value of `status_ok` returned by these routines can only be `.false.`.

**Comment by jacobwilliams** [comment]
Yes that does look like a bug!
