### ISSUE TITLE
How about adding `real32` support?

### ISSUE THREAD

**Issue by zoziha** [jacobwilliams/fortran-csv-module#19]
`csv-module` is very easy to use, thanks, @jacobwilliams !

#### Description

Both `real32` and `real64` are commonly used floating point precisions, although we can modify `wp=>real64` to `wp=>real32` in `csv_kinds`.
But if `csv-module` supports `real32` and `real64` at the same time, is it possible?

#### If it is worth a PR

I submitted [support for `real32` here](https://github.com/zoziha/fortran-csv-module/commit/11178d983a7cc8d9a8ae7b87bc732243ffeb17cb). I don’t know **if it is worth** submitting a PR?
What I did is:
- Add `sp=>real32` in `csv_kinds`;
- Add `to_real_sp`, rename `to_real` to `to_real_wp`;
- Add `get_real_sp_column`, rename `get_real_column` to `get_real_wp_column`;
- Add a `test_csv_sp` test.

#### Addition

[`toml-f`](https://github.com/toml-f/toml-f/blob/cd449a7dc40240dcbaa6d2196fb0c7748c704fd0/src/tomlf/build/table.f90#L72) also only supports double precision at the beginning, maybe for convenience, it now supports single precision and double precision floating point types.

**Comment by jacobwilliams** [comment]
Yes, I'd be happy to accept a PR to add `real32` support.
