### ISSUE TITLE
Error while reading

### ISSUE THREAD

**Issue by GHNewbiee** [jacobwilliams/fortran-csv-module#26]
While reading a file the following message is displayed:

```terminal
 /home/.../data/test.csv
At line 302 of file build/dependencies/fortran-csv-module/src/csv_module.F90
Fortran runtime error: Index '2' of dimension 1 of array 'row_data' above upper bound of 1
```
The code as partially follows:

```fortran
type(csv_file) :: file
logical        :: status_ok

print *, path
call file%read(path,header_row=1,status_ok=status_ok)
```

*test.csv*

```
"header1", "header2"
"text1",      -2.73
"text2",       0.24
...
```
Please advise. *Tia*

**Comment by jacobwilliams** [comment]
I don't get that error when reading this file. Probably there is some other bug in your code? Without the full code I can't really say.

**Comment by GHNewbiee** [comment]
There were blank lines in the end of the file. After deleting them, the file was successfully parsed. I apologize for any inconvenience.
