### ISSUE TITLE
Accuracy of reading values changes

### ISSUE THREAD

**Issue by GHNewbiee** [jacobwilliams/fortran-csv-module#30]
I read from a csv file, having among the others, a column with real numbers with variable decimal length but not more than 4 digits.

What I have observed after printing **ALL** real numbers is their accuracy has changed eg.

```
initial real number: 14.32
printed real number: 14:31999997 (*)
```

(*) Maybe the length of the decimal part is not correct. 

Is there any reason why that happens? is there anything I can do to get the original numbers?

*Tia*

**Comment by jacobwilliams** [comment]
Can you provide an example code where this happens?

**Comment by GHNewbiee** [comment]
Hmm, I have had the code recompiled and now it prints the figures correct. I may get old for coding! I think it's time for retirement!
