### ISSUE TITLE
gfortran>11 bug reading string column

### ISSUE THREAD

**Issue by epagone** [jacobwilliams/fortran-csv-module#32]
```bash
$ fpm new fcsv-bug --app
$ cd fcsv-bug
$ cat fpm.toml
...
[dependencies]
fortran-csv-module = { git="https://github.com/jacobwilliams/fortran-csv-module.git" }
```
```bash
$ cat app/main.f90
program main

use csv_module
use iso_fortran_env, only: wp => real64

implicit none

type(csv_file) :: f
logical :: status_ok
character(len=30),dimension(:),allocatable :: header, col1
integer :: i

! set optional inputs:
call f%initialize(verbose = .true.)

! open the file
call f%open('test.csv',n_cols=4,status_ok=status_ok)

! add header
call f%add(['x','y','z','t'])
call f%next_row()

! add some data:
call f%add([1.0_wp,2.0_wp,3.0_wp],real_fmt='(F5.3)')
call f%add(.true.)
call f%next_row()
call f%add([4.0_wp,5.0_wp,6.0_wp],real_fmt='(F5.3)')
call f%add(.false.)
call f%next_row()

! finished
call f%close(status_ok)

! read the file
call f%read('test.csv',header_row=1,status_ok=status_ok)

! get the header and type info
call f%get_header(header,status_ok)

print "(*(g0))", "HEADER:"
do i = 1, size(header)
  print "(*(g0))", ">"//trim(header(i))//"<"
end do

call f%get(1,col1,status_ok)

print "(*(g0))", "col1:"
do i = 1, size(col1)
  print "(*(g0))", ">",trim(col1(i)),"<"
end do

! destroy the file
call f%destroy()

end program main
```
```bash
$ fpm run --compiler gfortran-11
main.f90                               done.
fcsv-bug                               done.
[100%] Project compiled successfully.
HEADER:
>x<
>y<
>z<
>t<
col1:
>1.000<
>4.000<
$ gfortran-11 --version
GNU Fortran (Ubuntu 11.4.0-2ubuntu1~20.04) 11.4.0
```
```bash
$ fpm run --compiler gfortran-13
main.f90                               done.
fcsv-bug                               done.
[100%] Project compiled successfully.
HEADER:
>x<
>y<
>z<
>t<
col1:
>14.000<
> <
$ gfortran-13 --version
GNU Fortran (GCC) 13.2.0
```

**Comment by jacobwilliams** [comment]
There is some code in there to workaround bugs in gfortran:

```fortran
#if defined __GFORTRAN__
            ! the following is a workaround for gfortran bugs:
            select type (r)
            type is (character(len=*))
                tmp = repeat(' ',len(r)) ! size the string
                call me%csv_get_value(i,icol,tmp,status_ok)
                r(i) = tmp
            class default
                call me%csv_get_value(i,icol,r(i),status_ok)
            end select
#else
            call me%csv_get_value(i,icol,r(i),status_ok)
#endif
```

It appears that now, in 12.3.0, the workaround doesn't work, but the original code does.

**Comment by jacobwilliams** [comment]
I you comment out that workaround, does it work with 11 and 13?

**Comment by epagone** [comment]
> There is some code in there to workaround bugs in earlier versions of gfortran:
> 
> ```fortran
> #if defined __GFORTRAN__
>             ! the following is a workaround for gfortran bugs:
>             select type (r)
>             type is (character(len=*))
>                 tmp = repeat(' ',len(r)) ! size the string
>                 call me%csv_get_value(i,icol,tmp,status_ok)
>                 r(i) = tmp
>             class default
>                 call me%csv_get_value(i,icol,r(i),status_ok)
>             end select
> #else
>             call me%csv_get_value(i,icol,r(i),status_ok)
> #endif
> ```
> 
> It appears that now, in 12.3.0, the workaround doesn't work, but the original code does.

I see. Is it possible to use some preprocessor directive to check for the specific gfortran version and branch execution accordingly?

> I you comment out that workaround, does it work with 11 and 13?

What I tried to show opening the issue is that gfortran 11.4.0 works already now without any change, simply cloning (via fpm, but it's irrelevant, I guess) this repository. gfortran 12 and 13 seem to not work and, as you suggest, this can be rectified removing the workaround. Hence, my previous question in this message to use the workaround only when necessary using a preprocessor directive (if exists) that checks the compiler version.

**Comment by jacobwilliams** [comment]
I'd need to look into the preprocessor directives to see if we can check for specific gfortran versions.

I should add to the CI to test multiple versions also so we can verify which versions need or don't need it.

At some point I can just stop supporting old buggy gfortrans and just remove this workaround. I don't remember what version needed it.

**Comment by jacobwilliams** [comment]
OK, testing gfortran 9,10,11,12 now in the CI. Any version <= 10 will use the workaround.

**Comment by epagone** [comment]
Thank you
