### ISSUE TITLE
f%add([...]) first array entry ignored?

### ISSUE THREAD

**Issue by Knowledge91** [jacobwilliams/fortran-csv-module#4]
I copied your example for writing a CSV file, but 
`call f%add(['x','y','z','t'])` is writing the `x` into the row. 
My total output is given by:
```
 "y","z","t","�"
1.000,2.000,3.000,T
4.000,5.000,6.000,F
```

---
I am using OSX with `gfortran 7.2.0` with the command `gfortran main.f90 -L fortran-csv-module/lib/ -lcsv`

**Comment by jacobwilliams** [comment]
I can confirm this. It works fine with the intel compiler, so I suspect it is a gfortran compiler but. I'll look into it.

**Comment by jacobwilliams** [comment]
I think it should be fixed now. It was a gfortran compiler bug, so I added a weird workaround that seemed to make it work. Let me know if there are any other problems.
