### ISSUE TITLE
compiling problem with gfortran

### ISSUE THREAD

**Issue by Maselko** [jacobwilliams/fortran-csv-module#6]
my gFortran shows this error when I compile "csv_module.f90"

csv_module.f90:497:2:

  497 | #if defined __GFORTRAN__
      |  1
Warning: Illegal preprocessor directive
csv_module.f90:505:2:

  505 | #else
      |  1
Warning: Illegal preprocessor directive
csv_module.f90:507:2:

  507 | #endif
      |  1
Warning: Illegal preprocessor directive
csv_module.f90:915:2:

  915 | #if defined __GFORTRAN__
      |  1
Warning: Illegal preprocessor directive
csv_module.f90:925:2:

  925 | #else
      |  1
Warning: Illegal preprocessor directive
csv_module.f90:927:2:

  927 | #endif
      |  1
Warning: Illegal preprocessor directive

can you help me please?
Thank you

**Comment by jacobwilliams** [comment]
Did you change the file extension from `.F90` to `.f90`? The `.F90` extension enables the preprocessor. See https://gcc.gnu.org/onlinedocs/gfortran/Preprocessing-Options.html

**Comment by jg110** [comment]
Works fine for me building with gfortran 9.2.1.
